require("buffer");

import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import type { Metadata } from "next";
// import { TonConnectUIProvider } from "@tonconnect/ui-react";
import { Provider } from "@/components/Provider";
import Layout from "@/components/Layout/Layout";
import { TmaSDKLoader } from "@/components/TmaSDKLoader";
import { TonConnectUIProvider } from "@tonconnect/ui-react";
import { useEffect } from "react";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <TonConnectUIProvider
        manifestUrl="https://syntax-tma.vercel.app/tonconnect-manifest.json"
        actionsConfiguration={{
          twaReturnUrl: "https://t.me/DEC42_Syntax_BOT/MBTI",
        }}
      >
        {/* <TmaSDKLoader> */}
        <Provider>
          <Toaster />
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </Provider>
        {/* </TmaSDKLoader> */}
      </TonConnectUIProvider>
    </>
  );
}
